[FE] Make the initial introductory pages.
devlup-labs/iitj-omegle pull request #10
Opened 2023-04-24 05:07 UTC by boku13

Finished the UI for the main landing/sign-in page. 
![image](https://user-images.githubusercontent.com/120317108/233904502-c525e633-f3fc-46b3-b78f-50942e6f039c.png)

Made a page for introductory cards that let the user know how to use the site and who it's intended for.
![image](https://user-images.githubusercontent.com/120317108/233904606-7633b6c5-0e03-4504-ac2f-97b73f89ffb6.png)

Will integrate the cards into the landing page later.

2023-04-24 06:18 UTC, kunal-gg requested changes

2023-04-24 06:18 UTC, kunxl-gg commented on pages/_document.tsx
> +        </body>
What is the point of changing this file?

2023-04-24 06:18 UTC, kunal-gg commented on pages/info.tsx
> +    //used next-ui but later switched to tailwind
Remove this redundant code

2023-04-24 06:19 UTC, kunal-gg commented on pages/info.tsx
> +    //used next-ui but later switched to tailwind
I am referring to the comments.

2023-04-24 14:50 UTC, boku13 commented on pages/_document.tsx
> +        </body>
> What is the point of changing this file?

It was to get Next-UI to work, thought I'd leave it in case, we decided to go ahead with it.

2023-04-24 14:51 UTC, boku13 commented on pages/info.tsx
> +    //used next-ui but later switched to tailwind
sure.

2023-04-27 18:24 UTC, kunal-gg approved these changes

2023-04-27 18:25 UTC, merged